### ISSUE TITLE
Documentation on Docker setup

### ISSUE THREAD

**Issue by codelitt** [medivo/slack-responder#1]
This seems really useful. It would help if there was a bit of documentation about how the Docker integration works. Without a Dockerfile, I'm a little unsure of how the files you have for Docker are used.

**Comment by MrPowers** [comment]
Thanks for the comment!  The Docker stuff doesn't really have any business being in this repo, so I deleted the files.  I forgot we had those files in there, so thanks again for opening this issue!  I'm going to push up some new commands to this repo today (a generic command for creating Trello cards on any board/list and a command for retros), so stay tuned!

**Comment by codelitt** [comment]
Ahh cool. No problem then I'll use my own Docker setup. I'll keep an eye on the repo for changes.
